[flags]
time_delta = 10000
processes.default_memory_value = true
show_table_scroll_position = true

[cpu]
default = "average"

[memory]
legend_position = "top-left"

[network]
legend_position = "top-left"

[network.interface_filter]
is_list_ignored = false
regex = true
list = ["eth.+", "en.+", "wl.+"]

[processes]
default_grouped = true

[disk.mount_filter]
list = ["/boot"]

[[row]]
	ratio=3
	[[row.child]]
	type="cpu"
[[row]]
	ratio=3
	[[row.child]]
		type="mem"
	[[row.child]]
		type="temp"
	[[row.child]]
		type="disk"
[[row]]
	ratio=4
	[[row.child]]
		type="net"
	[[row.child]]
		ratio=2
		type="proc"
		default=true
